FROM mysql/mysql-server:latest

ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin@react_native_journey
ENV MYSQL_DATABASE=react_native_journey_db
ENV MYSQL_ROOT_PASSWORD=admin@react_native_journey

EXPOSE 3306